import { useEffect,useState } from 'react'
import { Alert,AlertDescription } from './components/ui/alert'
import { Badge } from './components/ui/badge'
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from './components/ui/card'
import { Input } from './components/ui/input'
import { Label } from './components/ui/label'
import { Select } from './components/ui/select'
import { EmptyState, PageToolbar } from './components/ui/page'
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from './components/ui/table'
import { formatWibDateTime } from './lib/wib'
type Log={id:string;userId?:string;action:string;resource:string;detail:string;createdAt:string};const apiBase=import.meta.env.VITE_API_BASE_URL||'/api'
export function AuditLogs({token}:{token:string}){const[logs,setLogs]=useState<Log[]>([]),[action,setAction]=useState(''),[resource,setResource]=useState(''),[error,setError]=useState('');function load(){const q=new URLSearchParams();if(action)q.set('action',action);if(resource)q.set('resource',resource);void request('/audit-logs?'+q,token).then(setLogs).catch(e=>setError(String(e)))}useEffect(load,[token,action,resource]);return <div className='space-y-4'><PageToolbar title="Audit Log & Riwayat Sistem" description="250 aktivitas sensitif terbaru yang dicatat backend secara otomatis."/><Card className="rounded-2xl border border-border bg-card shadow-2xs"><CardHeader className="border-b border-border/60"><CardTitle>Filter Audit Log</CardTitle><CardDescription>Saring berdasarkan aksi dan modul sistem.</CardDescription></CardHeader><CardContent className='grid gap-4 sm:grid-cols-2 pt-6'><div className='grid gap-2'><Label className="font-semibold text-xs text-foreground">Filter Aksi</Label><Select value={action} onChange={e=>setAction(e.target.value)}><option value=''>Semua aksi</option>{['login','create','update','delete','import','promote'].map(v=><option key={v}>{v}</option>)}</Select></div><div className='grid gap-2'><Label className="font-semibold text-xs text-foreground">Filter Modul</Label><Input value={resource} onChange={e=>setResource(e.target.value)} placeholder='Contoh: user, tutor, kelas'/></div></CardContent></Card>{error&&<Alert className='border-destructive/40 text-destructive'><AlertDescription>{error}</AlertDescription></Alert>}<Card className="rounded-2xl border border-border bg-card shadow-2xs overflow-hidden"><Table><TableHeader><TableRow className="border-b border-border"><TableHead>Waktu</TableHead><TableHead>Aksi</TableHead><TableHead>Modul</TableHead><TableHead>Detail</TableHead><TableHead>User ID</TableHead></TableRow></TableHeader><TableBody>{logs.map(l=><TableRow key={l.id}><TableCell className='whitespace-nowrap font-medium text-xs text-foreground'>{formatWibDateTime(l.createdAt)}</TableCell><TableCell><Badge variant='outline' className="font-semibold text-xs">{l.action}</Badge></TableCell><TableCell className="text-xs font-medium">{l.resource}</TableCell><TableCell className='max-w-xs truncate text-muted-foreground text-xs'>{l.detail||'-'}</TableCell><TableCell className='font-mono text-xs text-muted-foreground'>{l.userId||'-'}</TableCell></TableRow>)}{!logs.length&&<EmptyState colSpan={5} label='Belum ada aktivitas yang cocok.'/>}</TableBody></Table></Card></div>}
async function request(path:string,token:string){const r=await fetch(apiBase+path,{credentials:'include',headers:{Authorization:`Bearer ${token}`}});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||'Permintaan gagal');return result}
