import { useEffect,useState,type FormEvent } from 'react'
import { Alert,AlertDescription } from './components/ui/alert'
import { Button } from './components/ui/button'
import { FormCard } from './components/ui/page'
import { Label } from './components/ui/label'
import { Select } from './components/ui/select'
type Row=Record<string,unknown>&{id:string};const apiBase=import.meta.env.VITE_API_BASE_URL||'/api'
export function ClassEditor({classRow,token,close,saved}:{classRow:Row;token:string;close:()=>void;saved:()=>void}){const[tutors,setTutors]=useState<Row[]>([]),[message,setMessage]=useState('');useEffect(()=>{void request('/tutor',token).then(setTutors).catch(e=>setMessage(String(e)))},[token]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const wali=String(new FormData(e.currentTarget).get('waliKelasId')||'');const body={jenjang:classRow.jenjang,namaRombel:classRow.namaRombel,pokjarId:classRow.pokjarId,tahunAjaranId:classRow.tahunAjaranId,waliKelasId:wali||null};try{await request('/kelas/'+classRow.id,token,'PUT',body);saved();close()}catch(err){setMessage(String(err))}}return <FormCard title={`Ubah wali kelas: Kelas ${String(classRow.jenjang)}${String(classRow.namaRombel)}`} description='Riwayat wali kelas lama ditutup otomatis ketika perubahan disimpan.'><form className='space-y-4' onSubmit={submit}><div className='grid gap-2'><Label>Wali kelas</Label><Select name='waliKelasId' defaultValue={String(classRow.waliKelasId||'')}><option value=''>Belum ditetapkan</option>{tutors.map(t=><option key={t.id} value={t.id}>{String(t.nama)}</option>)}</Select></div><div className='flex gap-2'><Button>Simpan perubahan</Button><Button type='button' variant='outline' onClick={close}>Batal</Button></div>{message&&<Alert><AlertDescription>{message}</AlertDescription></Alert>}</form></FormCard>}
async function request(path:string,token:string,method='GET',body?:unknown){const r=await fetch(apiBase+path,{method,credentials:'include',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||'Permintaan gagal');return result}
