import { useEffect,useState } from 'react'
import { Badge } from './components/ui/badge'
import { Button } from './components/ui/button'
import { Card,CardContent,CardHeader,CardTitle } from './components/ui/card'
import { EmptyState } from './components/ui/page'
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from './components/ui/table'
import { formatWibDate } from './lib/wib'
type Row=Record<string,unknown>&{id:string};const apiBase=import.meta.env.VITE_API_BASE_URL||'/api'
export function ClassHistory({classID,title,token,close}:{classID:string;title:string;token:string;close:()=>void}){const[rows,setRows]=useState<Row[]>([]),[error,setError]=useState('');useEffect(()=>{void fetch(apiBase+'/kelas/'+classID+'/riwayat-wali',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Permintaan gagal');setRows(b)}).catch(e=>setError(String(e)))},[classID,token]);return <Card className='mb-4'><CardHeader className='flex-row items-center justify-between space-y-0'><CardTitle>Riwayat wali kelas: {title}</CardTitle><Button variant='outline' size='sm' onClick={close}>Tutup</Button></CardHeader><CardContent>{error&&<p className='mb-3 text-sm text-destructive'>{error}</p>}<Table><TableHeader><TableRow><TableHead>Wali kelas</TableHead><TableHead>Mulai</TableHead><TableHead>Selesai</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id}><TableCell className='font-medium'>{String((r.tutor as Row)?.nama||'-')}</TableCell><TableCell>{formatWibDate(r.tanggalMulai)}</TableCell><TableCell>{r.tanggalSelesai?formatWibDate(r.tanggalSelesai):'-'}</TableCell><TableCell><Badge variant={r.tanggalSelesai?'outline':'secondary'}>{r.tanggalSelesai?'Selesai':'Aktif'}</Badge></TableCell></TableRow>)}{!rows.length&&<EmptyState colSpan={4} label='Belum ada riwayat wali kelas.'/>}</TableBody></Table></CardContent></Card>}
