import { useState, type FormEvent, type ReactNode } from 'react'
import { toast } from 'sonner'
import { Button } from './components/ui/button'
import { FormCard } from './components/ui/page'
import { Input } from './components/ui/input'
import { Label } from './components/ui/label'
import { Select } from './components/ui/select'
import { wibDateInputValue } from './lib/wib'
type Row=Record<string,unknown>&{id:string};type Options={kelas:Row[];pokjar:Row[];parents:Row[]};const apiBase=import.meta.env.VITE_API_BASE_URL||'/api'
export function StudentEditor({row,options,token,close,saved}:{row?:Row;options:Options;token:string;close:()=>void;saved:()=>void}){const[submitting,setSubmitting]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSubmitting(true);try{const body=Object.fromEntries(new FormData(e.currentTarget));if(!row&&body.status==='')body.status='aktif';const r=await fetch(apiBase+'/peserta-didik'+(row?'/'+row.id:''),{method:row?'PUT':'POST',credentials:'include',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||'Permintaan gagal');toast.success(row?'Peserta didik diperbarui.':'Peserta didik ditambahkan.');saved();close()}catch(err:any){toast.error(`Gagal menyimpan: ${String(err.message||err)}`)}finally{setSubmitting(false)}}return <FormCard title={`${row?'Ubah':'Tambah'} peserta didik`} description='Data identitas dan penempatan rombel peserta didik.'><form className='grid gap-4 sm:grid-cols-2 lg:grid-cols-4' onSubmit={e=>void submit(e)}><Field label='Nama lengkap'><Input name='nama' defaultValue={String(row?.nama||'')} required/></Field><Field label='Jenis kelamin'><Select name='jenisKelamin' defaultValue={String(row?.jenisKelamin||'L')}><option>L</option><option>P</option></Select></Field><Field label='NIS'><Input name='nis' defaultValue={String(row?.nis||'')} required/></Field><Field label='NISN'><Input name='nisn' defaultValue={String(row?.nisn||'')} required/></Field><Field label='NIK anak'><Input name='nik' defaultValue={String(row?.nik||'')} required placeholder='16 digit NIK'/></Field><Field label='Tanggal Lahir'><Input name='tanggalLahir' type='date' defaultValue={wibDateInputValue(row?.tanggalLahir)}/></Field><Picker label='Kelas' name='kelasId' rows={options.kelas} value={String(row?.kelasId||'')} kind='class'/><Picker label='Pokjar asal' name='pokjarId' rows={options.pokjar} value={String(row?.pokjarId||'')} kind='pokjar'/><Picker label='Orang tua' name='orangTuaId' rows={options.parents} value={String(row?.orangTuaId||'')} kind='parent'/><Field label='Status'><Select name='status' defaultValue={String(row?.status||'aktif')}><option>aktif</option><option>pindah</option><option>keluar</option><option>lulus</option></Select></Field><div className='flex gap-2 sm:col-span-2 lg:col-span-4'><Button disabled={submitting}>{submitting?'Menyimpan...':'Simpan'}</Button><Button variant='outline' type='button' onClick={close}>Batal</Button></div></form></FormCard>}
function Field({label,children}:{label:string;children:ReactNode}){return <div className='grid gap-2'><Label>{label}</Label>{children}</div>}
function Picker({label,name,rows,value,kind}:{label:string;name:string;rows:Row[];value:string;kind:string}){return <Field label={label}><Select name={name} defaultValue={value} required><option value=''>Pilih {label.toLowerCase()}</option>{rows.map(r=><option key={r.id} value={r.id}>{kind==='class'?`Kelas ${String(r.jenjang)}${String(r.namaRombel)}`:kind==='pokjar'?String(r.namaPokjar):parentLabel(r)}</option>)}</Select></Field>}
function parentLabel(r:Row){const b=String(r.namaBapak||'');const i=String(r.namaIbu||'');const na=String(r.nikAyah||'');const ni=String(r.nikIbu||'');const base=`Bpk. ${b||'-'} / Ibu ${i||'-'}`;const nik=na||ni;return nik?`${base} — NIK ${nik}`:base}
